--1
CREATE TABLESPACE TS_KAA
DATAFILE 'TS_KAA.dbf'
SIZE 7M
AUTOEXTEND ON
NEXT 5M
MAXSIZE 20M;

--2
CREATE TEMPORARY TABLESPACE TS_KAA_TEMP
TEMPFILE 'TS_KAA_TEMP.dbf'
SIZE 5M
AUTOEXTEND ON
NEXT 3M
MAXSIZE 30M;

--3
SELECT TABLESPACE_NAME FROM DBA_TABLESPACES;

SELECT FILE_NAME, TABLESPACE_NAME, BYTES / 1024 / 1024 AS SIZE_MB
FROM DBA_DATA_FILES;

--4
CREATE ROLE C##RL_KAA_CORE;

GRANT CREATE SESSION TO C##RL_KAA_CORE;
GRANT CREATE TABLE TO C##RL_KAA_CORE;
GRANT CREATE VIEW TO C##RL_KAA_CORE;
GRANT CREATE ANY PROCEDURE TO C##RL_KAA_CORE;
--GRANT CREATE ANY FUNCTION TO C##RL_KAA_CORE;
GRANT DROP ANY TABLE TO C##RL_KAA_CORE;
GRANT DROP ANY VIEW TO C##RL_KAA_CORE;
GRANT DROP ANY PROCEDURE TO C##RL_KAA_CORE;
--GRANT DROP ANY FUNCTION TO C##RL_KAA_CORE;

--5
SELECT ROLE FROM DBA_ROLES WHERE ROLE = 'C##RL_KAA_CORE';

SELECT GRANTEE,
       GRANTED_ROLE,
       ADMIN_OPTION,
       DELEGATE_OPTION,
       DEFAULT_ROLE,
       COMMON,
       INHERITED
FROM DBA_ROLE_PRIVS
WHERE GRANTED_ROLE = 'C##RL_KAA_CORE';

--6
CREATE PROFILE C##PF_KAA_CORE LIMIT
   PASSWORD_LIFE_TIME 180
   SESSIONS_PER_USER 3
   FAILED_LOGIN_ATTEMPTS 7
   PASSWORD_LOCK_TIME 1
   PASSWORD_REUSE_TIME 10
   PASSWORD_GRACE_TIME DEFAULT
   PASSWORD_REUSE_MAX 5
   CONNECT_TIME 180
   IDLE_TIME 30;

--7
SELECT PROFILE FROM DBA_PROFILES;

SELECT PROFILE, RESOURCE_NAME, LIMIT
FROM DBA_PROFILES
WHERE PROFILE = 'C##PF_KAA_CORE';

SELECT PROFILE, RESOURCE_NAME, LIMIT
FROM DBA_PROFILES
WHERE PROFILE = 'DEFAULT';

--8
ALTER SESSION SET CONTAINER = XEPDB1;
SELECT SYS_CONTEXT('USERENV', 'CON_NAME') FROM DUAL;
SELECT TABLESPACE_NAME FROM DBA_TABLESPACES;

CREATE TABLESPACE TS_KAA
DATAFILE 'TS_KAA_01.dbf'
SIZE 7M 
AUTOEXTEND ON NEXT 5M MAXSIZE 20M;

CREATE TEMPORARY TABLESPACE TS_KAA_TEMP
TEMPFILE 'TS_KAA_TEMP_01.dbf'
SIZE 5M 
AUTOEXTEND ON NEXT 3M MAXSIZE 30M;


CREATE USER KAA_CORE
IDENTIFIED BY pass1234
DEFAULT TABLESPACE TS_KAA
TEMPORARY TABLESPACE TS_KAA_TEMP
PROFILE C##PF_KAA_CORE;

ALTER USER KAA_CORE ACCOUNT UNLOCK;

ALTER USER KAA_CORE PASSWORD EXPIRE;

--9
--CONNECT system/1234@localhost AS SYSDBA 
ALTER USER KAA_CORE IDENTIFIED BY newpassword;
ALTER USER KAA_CORE IDENTIFIED BY new_password; 

--10
CREATE TABLE test_table (
    id NUMBER PRIMARY KEY,
    name VARCHAR2(50)
);

CREATE VIEW test_view AS
SELECT id, name
FROM test_table;

--11
CREATE TABLESPACE KAA_QDATA
DATAFILE 'KAA_QDATA.dbf'
SIZE 10M
OFFLINE;

CREATE USER KAA
IDENTIFIED BY pass1234
DEFAULT TABLESPACE TS_KAA
TEMPORARY TABLESPACE TS_KAA_TEMP
PROFILE C##PF_KAA_CORE;

ALTER TABLESPACE KAA_QDATA ONLINE;

ALTER USER KAA QUOTA 2M ON KAA_QDATA;

CREATE TABLE KAA_QDATA_TABLE (
    id NUMBER PRIMARY KEY,
    data VARCHAR2(50)
) TABLESPACE KAA_QDATA;

INSERT INTO KAA_QDATA_TABLE (id, data) VALUES (1, 'Data 1');
INSERT INTO KAA_QDATA_TABLE (id, data) VALUES (2, 'Data 2');
INSERT INTO KAA_QDATA_TABLE (id, data) VALUES (3, 'Data 3');
COMMIT;

