--1
SELECT NAME, OPEN_MODE FROM V$PDBS;
SELECT pdb_name, pdb_id, status FROM SYS.dba_pdbs;
ALTER PLUGGABLE DATABASE KAA_PDB OPEN;

--2
SELECT INSTANCE_NAME FROM V$INSTANCE;

--3
SELECT COMP_ID, VERSION, STATUS FROM DBA_REGISTRY;

--4
CREATE PLUGGABLE DATABASE KAA_PDB
ADMIN USER pdb_admin IDENTIFIED BY pass1234
ROLES = (DBA)
FILE_NAME_CONVERT = ('C:\APP\WIN10\PRODUCT\21C\ORADATA\XE\PDBSEED', 'C:\APP\WIN10\PRODUCT\21C\ORADATA\XE\KAA_PDB');

--5
SELECT name, open_mode FROM v$pdbs;

--6
CREATE TABLESPACE TS_KAA
DATAFILE 'TS_PDB.dbf'
SIZE 7M
AUTOEXTEND ON NEXT 5M
MAXSIZE 30M;

CREATE TEMPORARY TABLESPACE TS_KAA_TEMP
TEMPFILE 'TS_PDB_TEMP.dbf'
SIZE 5M
AUTOEXTEND ON NEXT 3M
MAXSIZE 30M;

alter session set "_ORACLE_SCRIPT" = true;

CREATE ROLE RL_PDB_KAA;
GRANT ALL PRIVILEGES TO RL_PDB_KAA;
GRANT CREATE SESSION TO RL_PDB_KAA;
COMMIT;

CREATE PROFILE PF_PDB_KAA LIMIT
PASSWORD_LIFE_TIME 180
SESSIONS_PER_USER 3
FAILED_LOGIN_ATTEMPTS 7
PASSWORD_LOCK_TIME 1
PASSWORD_REUSE_TIME 10
PASSWORD_GRACE_TIME DEFAULT
CONNECT_TIME 180
IDLE_TIME 30;

CREATE USER U1_KAA_PDB IDENTIFIED BY pass1234
PROFILE PF_PDB_KAA
ACCOUNT UNLOCK;

ALTER USER U1_KAA_PDB QUOTA 2M ON TS_KAA;

GRANT RL_PDB_KAA TO U1_KAA_PDB;

--7
CREATE TABLE KAA_table
(
    Name nvarchar2(20),
    NumberOfGroup number(2)
)TABLESPACE TS_KAA;

DROP TABLE KAA_TABLE;

INSERT INTO KAA_TABLE (Name, NumberOfGroup) VALUES ('Арсений', 6);
INSERT INTO KAA_TABLE (Name, NumberOfGroup) VALUES ('Влад', 4);
INSERT INTO KAA_TABLE (Name, NumberOfGroup) VALUES ('Влад', 6);
INSERT INTO KAA_TABLE (Name, NumberOfGroup) VALUES ('Александр', 6);
INSERT INTO KAA_TABLE (Name, NumberOfGroup) VALUES ('Илья', 4);
INSERT INTO KAA_TABLE (Name, NumberOfGroup) VALUES ('Александр', 4);


SELECT * FROM KAA_table WHERE NumberOfGroup = 6;
SELECT * FROM KAA_table WHERE Name = 'Илья';

--8
SELECT TABLESPACE_NAME, STATUS, CONTENTS FROM USER_TABLESPACES;
SELECT TABLESPACE_NAME, FILE_NAME FROM DBA_DATA_FILES;
SELECT TABLESPACE_NAME, FILE_NAME FROM DBA_TEMP_FILES;
SELECT * FROM DBA_ROLES;
SELECT * FROM DBA_ROLE_PRIVS ORDER BY GRANTEE;
SELECT * FROM DBA_PROFILES ORDER BY PROFILE;
SELECT * FROM DBA_USERS ORDER BY USERNAME;
SELECT USERNAME, GRANTED_ROLE FROM DBA_USERS JOIN DBA_ROLE_PRIVS ON USERNAME = GRANTEE ORDER BY USERNAME;

--9
CREATE USER C##KAA1 IDENTIFIED BY pass1234 CONTAINER=ALL;
GRANT CREATE SESSION TO C##KAA1 CONTAINER=ALL;
GRANT CONNECT TO C##KAA1 CONTAINER=ALL;

SELECT * FROM V$PDBS;
SELECT * FROM DBA_USERS WHERE USERNAME = 'C##KAA';

SELECT * FROM BD

--10
GRANT CONNECT TO C##YYY CONTAINER=ALL;
SELECT * FROM DBA_USERS WHERE USERNAME = 'C##YYY';


--11
SELECT NAME, OPEN_MODE FROM V$PDBS;

SELECT TABLE_NAME FROM ALL_TABLES WHERE OWNER = 'C##KAA';
SELECT * FROM DBA_ROLES;
SELECT * FROM DBA_PROFILES;

SELECT FILE_NAME, TABLESPACE_NAME FROM DBA_DATA_FILES WHERE TABLESPACE_NAME = 'TS_KAA_PDB';

--12
DROP PLUGGABLE DATABASE KAA_PDB INCLUDING DATAFILES;

SELECT FILE_NAME FROM DBA_DATA_FILES WHERE TABLESPACE_NAME = 'KAA_PDB';

DROP USER C##KAA CASCADE;






















