-- Задание №1
SELECT * FROM DBA_TABLESPACES;
SELECT * FROM DBA_DATA_FILES;
SELECT * FROM DBA_TEMP_FILES;

-- Задание №2
CREATE TABLESPACE KAA_QDATA
DATAFILE 'KAA_QDATA_01.dbf'
SIZE 10M
AUTOEXTEND ON NEXT 5M
MAXSIZE 30M
OFFLINE;

ALTER USER C##KAA QUOTA 2M ON KAA_QDATA;
ALTER TABLESPACE KAA_QDATA ONLINE;

CREATE TABLE KAA_T1
(
    Id number(6) primary key,
    Worker nvarchar2(20)
)TABLESPACE KAA_QDATA;

INSERT INTO KAA_T1 (Id, Worker) VALUES (1, 'Евген');
INSERT INTO KAA_T1 (Id, Worker) VALUES (2, 'Олег');
INSERT INTO KAA_T1 (Id, Worker) VALUES (3, 'Толик');

-- Задание №3
SELECT DISTINCT * FROM DBA_SEGMENTS WHERE TABLESPACE_NAME = 'KAA_QDATA';

-- Задание №4
DROP TABLE KAA_T1;
SELECT DISTINCT * FROM DBA_SEGMENTS WHERE TABLESPACE_NAME = 'KAA_QDATA';
SELECT * FROM USER_RECYCLEBIN;
COMMIT;
-- Задание №5
FLASHBACK TABLE KAA_T1 TO BEFORE DROP;
SELECT * FROM KAA_T1;

-- Задание №6
BEGIN
FOR k in 4..10000
    LOOP
    INSERT INTO KAA_T1 (Id) VALUES (k);
    end loop;
    COMMIT;
END;

-- Задание №7
SELECT SEGMENT_NAME, SEGMENT_TYPE, TABLESPACE_NAME, BYTES, BLOCKS, EXTENTS, BUFFER_POOL FROM DBA_SEGMENTS WHERE TABLESPACE_NAME = 'KAA_QDATA';
SELECT * FROM USER_EXTENTS WHERE TABLESPACE_NAME = 'KAA_QDATA';

-- Задание №8
DROP TABLESPACE KAA_QDATA INCLUDING CONTENTS AND DATAFILES;

-- Задание №9
SELECT GROUP#, STATUS, MEMBERS FROM V$LOG;

-- Задание №10
SELECT * FROM V$LOGFILE;

-- Задание №11
ALTER SYSTEM SWITCH LOGFILE;

SELECT TO_CHAR(SYSDATE, 'DD-MM-YYYY HH24:MI:SS') AS current_time 
FROM DUAL;

SELECT GROUP#, STATUS, MEMBERS FROM V$LOG;

-- Задание №12
ALTER DATABASE ADD LOGFILE GROUP 4 'C:\oracle\oradata\XE\redo04.log' SIZE 50M;

--ALTER DATABASE ADD LOGFILE GROUP 4 'C:\APP\WIN10\PRODUCT\21C\ORADATA\XE\redo04.log' SIZE 50M BLOCKSIZE 512;

ALTER DATABASE ADD LOGFILE MEMBER 'C:\oracle\oradata\XE\redo04_1.log' TO GROUP 4;

ALTER DATABASE ADD LOGFILE MEMBER 'C:\oracle\oradata\XE\redo04_2.log' TO GROUP 4;

ALTER DATABASE ADD LOGFILE MEMBER 'C:\oracle\oradata\XE\redo04_1.log' TO GROUP 4;
ALTER DATABASE ADD LOGFILE MEMBER 'C:\oracle\oradata\XE\redo04_2.log' TO GROUP 4;


--ALTER DATABASE ADD LOGFILE GROUP 4 'C:\APP\WIN10\PRODUCT\21C\ORADATA\XE\redo04.log' REUSE SIZE 50M BLOCKSIZE 512;

SELECT * FROM V$LOG;

SELECT GROUP#, MEMBER FROM V$LOGFILE;

SELECT GROUP#, STATUS FROM V$LOG;

ALTER SYSTEM SWITCH LOGFILE;

SELECT CURRENT_SCN FROM V$DATABASE;


ALTER DATABASE ADD LOGFILE GROUP 4 
  ('C:\APP\WIN10\PRODUCT\21C\ORADATA\XE\redo04a.log', 
   'C:\APP\WIN10\PRODUCT\21C\ORADATA\XE\redo04b.log', 
   'C:\APP\WIN10\PRODUCT\21C\ORADATA\XE\redo04c.log') 
SIZE 50M;


-- Задание №13
ALTER DATABASE DROP LOGFILE GROUP 4;
SELECT MEMBER FROM V$LOGFILE;


-- Задание №14
SELECT NAME, LOG_MODE FROM V$DATABASE;
SELECT INSTANCE_NAME, ARCHIVER, ACTIVE_STATE FROM V$INSTANCE;

SHUTDOWN IMMEDIATE;
STARTUP MOUNT;
ALTER DATABASE ARCHIVELOG;
ALTER DATABASE OPEN;
ARCHIVE LOG LIST;

SELECT INSTANCE_NAME, STATUS 
FROM V$INSTANCE;

SHUTDOWN ABORT;
STARTUP MOUNT;


-- Задание №17
SELECT * FROM V$LOG;
ALTER SYSTEM SET LOG_ARCHIVE_DEST_1 ='LOCATION=C:\APP\WIN10\PRODUCT\21C\ORADATA\XE\Archive';
ALTER SYSTEM SWITCH LOGFILE;
SELECT * FROM V$ARCHIVED_LOG;


SELECT THREAD#, SEQUENCE#, FIRST_CHANGE#, NEXT_CHANGE#
FROM V$ARCHIVED_LOG
ORDER BY SEQUENCE# DESC;
SELECT CURRENT_SCN FROM V$DATABASE;

ALTER SYSTEM ARCHIVE LOG CURRENT;

SELECT THREAD#, SEQUENCE#, NAME 
FROM V$ARCHIVED_LOG
ORDER BY SEQUENCE# DESC;


-- Задание №19
SELECT * FROM V$CONTROLFILE;
SELECT NAME FROM V$CONTROLFILE;
SELECT TYPE, RECORDS_TOTAL, RECORD_SIZE, RECORDS_USED 
FROM V$CONTROLFILE_RECORD_SECTION;
SELECT NAME, RESETLOGS_CHANGE# FROM V$DATABASE;



-- Задане №20 (В консоли)
-- В консоли: SHOW PARAMETER CONTROL;

-- Задание №21 (В консоли)
-- В консоли: SHOW PARAMERER spfile;
--SHOW PARAMETER spfile;


-- Задание №22
CREATE PFILE = 'KAA_PFILE.ora' FROM SPFILE;

-- Задание №23
show parameter remote_login_passwordfile;
SELECT * FROM V$PWFILE_USERS;


-- Задание №24
SELECT * FROM V$DIAG_INFO;

SELECT DISTINCT SEGMENT_TYPE FROM DBA_SEGMENTS;

--C:\APP\WIN10\PRODUCT\21C\diag\rdbms\xe\xe\trace

--Задание №25
SELECT VALUE FROM V$DIAG_INFO WHERE NAME = 'Diag Trace';

--ALTER SYSTEM SWITCH LOGFILE
